# Makefile for Sphinx documentation
#

.PHONY: all webdoc

all:
	cd en; $(MAKE) html
	cd ja; $(MAKE) html

online:
	cd en; $(MAKE) online
	cd ja; $(MAKE) online

clean:
	cd en; $(MAKE) clean
	cd ja; $(MAKE) clean
